Update open-ai-app.yml
release

diff --git a/.github/workflows/open-ai-app.yml b/.github/workflows/open-ai-app.yml
--- a/.github/workflows/open-ai-app.yml
+++ b/.github/workflows/open-ai-app.yml
@@ -8,6 +8,19 @@ on:
 
   # Allow manual workflow trigger
   workflow_dispatch:
+    inputs:
+      templateRelease:
+        description: 'What (existing or NEW) release tag to point the Helper to'
+        type: string
+        required: true
+      createRelease:
+        description: 'Create a NEW release with that tag'
+        type: boolean
+        required: false
+        default: true
+
+env:
+  templateRelease: ${{ github.event.inputs.templateRelease }}
 
 jobs:
   build:
@@ -54,38 +67,71 @@ jobs:
         with:
           name: Nextjs-site
           path: ./site-deploy/Nextjs-site.zip
-
-  deploy:
+  
+  CreateRelease:
     runs-on: ubuntu-latest
-    needs: build
-    environment:
-      name: "Production"
-
+    name: Create a Release
+    if: ${{ github.event.inputs.createRelease == 'true' }}
     steps:
+      - uses: actions/checkout@v3.3.0
+
       - name: ⬇️ Download artifact from build job
         uses: actions/download-artifact@v3
+        if: ${{ github.event.inputs.createRelease == 'true' }}
         with:
           name: Nextjs-site
 
-      - name: 🗝️ Azure Login
-        uses: azure/login@v1
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+      - name: Check that the GitHub release does not already exist
+        run: |
+          GHJSON=$(gh release view ${{env.templateRelease}} --json name) || GHJSON=""
 
-      # - name: 🚀 Deploy to Azure Web App
-      #   id: deploy-to-webapp
-      #   uses: azure/webapps-deploy@v2
-      #   with:
-      #     app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
-      #     package: ${{ github.workspace }}/Nextjs-site.zip
+          if [ -z "$GHJSON" ]
+          then
+                echo "Release not found - great"
+          else
+                echo "Release already exists - aborting"
+                exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Publish a Release
-        id: publish-release
-        uses: softprops/action-gh-release@v1
-        if: startsWith(github.ref, 'refs/tags/')
-        with:
-          files: |
-            ${{ github.workspace }}/Nextjs-site.zip
+      - name: Create GitHub release
+        run: |
+          GHJSON=$(gh release create ${{env.templateRelease}} '${{ github.workspace }}/Nextjs-site.zip' -p --generate-notes )
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   environment:
+  #     name: "Production"
 
-      - name: 🧹 Cleanup
-        run: rm ${{ github.workspace }}/Nextjs-site.zip
+  #   steps:
+  #     - name: ⬇️ Download artifact from build job
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: Nextjs-site
+
+  #     - name: 🗝️ Azure Login
+  #       uses: azure/login@v1
+  #       with:
+  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+  #     - name: 🚀 Deploy to Azure Web App
+  #       id: deploy-to-webapp
+  #       uses: azure/webapps-deploy@v2
+  #       with:
+  #         app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
+  #         package: ${{ github.workspace }}/Nextjs-site.zip
+
+  #     - name: Publish a Release
+  #       id: publish-release
+  #       uses: softprops/action-gh-release@v1
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       with:
+  #         files: |
+  #           ${{ github.workspace }}/Nextjs-site.zip
+
+  #     - name: 🧹 Cleanup
+  #       run: rm ${{ github.workspace }}/Nextjs-site.zip
